/*
  # Change leads ID to simple numeric format
  
  This migration changes the leads table ID from UUID to a simple
  auto-incrementing numeric ID with maximum 5 digits (10000-99999).
  
  1. Changes
    - Drop the existing leads table (since it's empty or for testing)
    - Recreate with numeric ID that auto-increments starting from 10000
    - Keep all other columns the same
    - Disable RLS (as it was previously disabled)
*/

-- Drop the existing leads table
DROP TABLE IF EXISTS leads CASCADE;

-- Create new leads table with numeric ID
CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1),
  email TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  company_name TEXT,
  project_description TEXT,
  status TEXT DEFAULT 'new',
  source TEXT DEFAULT 'CRM',
  notes TEXT,
  assigned_to UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Disable RLS for now
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON leads TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE leads_id_seq TO anon, authenticated, service_role;

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);